<?php

namespace App\ContactModule;

use Nette\Environment;
use Venne\Application\UI;

\App\RegisterModule\CaptchaControl::register();

/**
 * @resource ContactModule
 */
class DefaultPresenter extends \Venne\Developer\Presenter\FrontPresenter {


	/**
	 * @privilege read
	 */
	public function createComponentContactForm($name){
		$form = new \Venne\Forms\Form($this,$name);
		$form->addGroup("Kontaktní formulář");
		$form->addText('name', 'Jméno:')
		->setRequired('Zadejte prosím jméno');
		$form->addText('email', 'Email:')
		->setRequired('Zadejte prosím email')
		->addRule(\Nette\Application\UI\Form::EMAIL, 'Zadejte platný email');
		$form->addTextArea('message', 'Zpráva:')
		->addRule(\Nette\Application\UI\Form::MAX_LENGTH, 'Zpráva je příliš dlouhá', 1000)
		->setRequired('Zadejte prosím zprávu');
		$form->addCaptcha('captcha')
		->addRule(\Nette\Forms\Form::FILLED, "Opište text z obrázku.")
		->addRule($form["captcha"]->getValidator(), 'Špatně opsaný text. Zkuste to znovu')
		->setFontSize(25)
		->setLength(5) //word length
		->setTextMargin(20) //px, set text margin on left and rigth side
		->setTextColor(\Nette\Image::rgb(0,0,0)) //array("red" => 0-255, "green" => 0-255, "blue" => 0-255)
		->setBackgroundColor(\Nette\Image::rgb(230,230,230)) //array("red" => 0-255, "green" => 0-255, "blue" => 0-255)
		->setImageHeight(60) //px, if not set (0), image height will be generated by font size
		->setImageWidth(0) //px, if not set (0), image width will be generated by font size
		->setExpire(1000) //ms, set expiration time to seession
		->setFilterSmooth(false) //int or false (disable)
		->setFilterContrast(false)  //int or false (disable)
		->useNumbers(false); // bool or void
		$form->addSubmit('send', 'Odeslat');

		$form->onSuccess[] = callback($this, 'contactFormSubmitted');

		return $form;
	}

	public function renderDefault(){
		$this->template->entity = $this->context->services->contact->getRepository()->findOneBy(array("url" => "contact"));
		
	}

	public function contactFormSubmitted($form)
	{
		$values = $form->getValues();
		$msg = "Odesláno!";

		$mail = new \Nette\Mail\Message;
		$mail->setFrom("$values->name <$values->email>")  // gmail pravdepodobne ignoruje
		->addTo($this->context->params["adminMail"])
		->setSubject("Zpráva - Venne")
		->setBody($values->message);


		try {
			$this->send($mail);
		} catch (Exception $e) {
			$msg = "Odeslání selhalo!";
		}
		$this->flashMessage($msg);
		$this->redirect('this');

	}


	public function send($mail){
		$mailer = new \Nette\Mail\SmtpMailer($this->context->params["smtp"]);
		$mailer->send($mail);

	}



}
